/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ramamike.cat;

import com.ramamike.cat.models.Model;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    
    @Override
    public void start(Stage stage) {
	Model.getInstance().getViewFactory().showApp();
    }
}